
MTK_PLATFORM := $(subst ",,$(CONFIG_MTK_PLATFORM))
ARCH_MTK_PROJECT := $(subst ",,$(CONFIG_ARCH_MTK_PROJECT))

MTK_CUSTOM_PATH  := $(srctree)/drivers/misc/mediatek

# When environment not defined
ifeq ($(PROJECT_NAME),)
  $(warning -- PROJECT_NAME is null, please export PROJECT_NAME = wik_fr ---)
endif

# For cust_battery_meter_table.h cust_battery_meter.h 
CUST_PROJECT_DIR := $(PWD)/vendor/tinno/$(ARCH_MTK_PROJECT)/$(PROJECT_NAME)
ifneq ($(wildcard $(CUST_PROJECT_DIR)/kernel/power/cust_*.h),)
  ccflags-y += -I$(CUST_PROJECT_DIR)/kernel/power
  $(warning ---~~~~~$(CUST_PROJECT_DIR)/kernel/power/cust_*.h------exit~~~~~~~)
endif
